kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
      - aescbc:
        keys:
          - name: key1
            secret: C1YHyimQglsCuGxiX+igFtwGn2kBspwgLHTYGAWzjyk=
      - identity: {}
